# Generated by Django 4.2.7 on 2023-12-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("sub_title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("cover", models.ImageField(blank=True, null=True, upload_to="data/news/covers/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageViews",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("news_object", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.news")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
