# Generated by Django 4.2.7 on 2023-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_coursesubscription_course"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="course_cour_slug_235a66_idx"),
        ),
    ]
