# Generated by Django 4.2.7 on 2023-12-09 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_course_course_cour_slug_235a66_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="course_cour_slug_235a66_idx",
        ),
    ]
