# Generated by Django 4.2.7 on 2023-12-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_course_course_cour_slug_235a66_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lessons_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
