# Generated by Django 4.2.7 on 2023-12-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_alter_course_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
