# Generated by Django 4.2.7 on 2023-12-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0009_alter_course_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecomment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="course.course"
            ),
        ),
    ]
