# Generated by Django 4.2.7 on 2023-12-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0010_alter_coursecomment_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecomment",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
