# Generated by Django 4.2.7 on 2023-12-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0015_remove_courselesson_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="course.course"
            ),
        ),
    ]
